routes/web.php
<?php

use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\CategoriesController;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\TagsController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\FrontEndController;
use App\Http\Controllers\GeneralSettingsController;
use App\Http\Controllers\MailSettingsController;
use App\Http\Controllers\MediaController;
use App\Http\Controllers\PagesController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\SubCategoryController;
use App\Http\Controllers\TermPrivacyController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\BrandController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\ProductController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//login
Route::get('/', function () {
    return view('auth.login');
});
Route::match(['get', 'post'], '/login', [AdminController::class,'login'])->name('login');
//logout
Route::get('/logout', [AdminController::class,'logout'])->name('logout');
//terms & policy
Route::get('/privacy', [TermPrivacyController::class, 'index'])->name('termprivacy');
//Auth Admin Panel
Route::group(['middleware' => ['auth']], function () {
    //dashboard
    Route::get('/dashboard',[DashboardController::class,'dashboard'])->name('dashboard');
//users
Route::resource('users',UserController::class);
// roles
Route::resource('roles',RoleController::class);
// frontend
Route::resource('frontend',FrontEndController::class);
//Category
Route::resource('category',CategoriesController::class);
//Tag
Route::resource('tag',TagsController::class);
//Media
Route::resource('media',MediaController::class);
//Comment
Route::resource('comment',CommentController::class);
// Brand
Route::resource('brand',BrandController::class);
// Product
Route::resource('product',ProductController::class);
// Order
Route::resource('order',OrderController::class);
// General Settings
Route::resource('general',GeneralSettingsController::class);
// Mail Settings
Route::resource('mail',MailSettingsController::class);
// Page
Route::resource('page',PagesController::class);
// Post
Route::resource('post',PostController::class);
Route::any('post/{id}','PostController@edit')->name('post.edit');
// Privacy
Route::resource('privacy',TermPrivacyController::class);
// SubCategory
Route::resource('subcategory',SubCategoryController::class);
// Profile
Route::resource('profile',ProfileController::class);
// General Settings
Route::resource('general',GeneralSettingsController::class);

 //change password
 Route::get('/password', [AdminController::class,'changepassword'])->name('password.index');
 Route::put('/change-Password', [AdminController::class,'password_update'])->name('password.update');
});

app/Models/Comment.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Comment extends Model
{
    use HasFactory;
    protected $guarded = [];
    public function pos(){
        return $this->belongsTo('App\Models\Post','post_id');
    }
    public function usr(){
        return $this->belongsTo('App\Models\User','user_id');
    }
}

app/Http/Controllers/CommentController.php
<?php

namespace App\Http\Controllers;

use App\Models\Comment;
use App\Models\Post;
use Illuminate\Http\Request;

class CommentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $data = Comment::orderBy('id', 'DESC')->get();
        return view('Backend.Comment.index', compact('data'))
            ->with('i', ($request->input('page', 1) - 1) * 5);

    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $post = Post::all();
        $comment = Comment::all();
        return view('Backend.Comment.create',compact('post','comment'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'comment_done'=> 'required',
            'post_id' => 'required',
            'submitted_on' => 'required',
        ]);
        $input = $request->all();
        $comment = Comment::create($input);
        return redirect()->route('comment.index')
            ->with('success', 'Comment Created Successfully !!!',compact('comment'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Comment  $comment
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $comment = Comment::find($id);
        return view('Backend.Comment.show',compact('comment'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Comment  $comment
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $post = Post::all();
        $comment = Comment::find($id);

        return view('Backend.Comment.edit',compact('comment','post'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Comment  $comment
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'comment_done'=> 'required',
            'post_id' => 'required',
            'submitted_on' => 'required',
        ]);
        $input = $request->all();
        $comment = Comment::findOrfail($id);
        $comment->update($input);

        return redirect()->route('comment.index')
            ->with('success', 'Selected Comment Updated Successfully !!!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Comment  $comment
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $comment = Comment::find($id)->delete();
        return redirect()->route('comment.index')->with('success','Selected Comment Deleted Successfully!!!',compact('comment'));
    }
}

resources/views/Backend/Comment/create.blade.php
@extends('Backend.layouts.master')
@section('page_title',' Comment')
@section('content')
        <!-- ============================================================== -->
        <div class="page-wrapper">
            <!-- ============================================================== -->
            <!-- Bread crumb and right sidebar toggle -->
            <!-- ============================================================== -->
            <div class="page-breadcrumb">
                <div class="row">
                    <div class="col-12 d-flex no-block align-items-center">
                        <h4 class="page-title">Comment</h4>
                        <div class="ml-auto text-right">
                            <nav aria-label="breadcrumb">
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item"><a href="{{route('dashboard')}}">Home</a></li>
                                    <li class="breadcrumb-item active" aria-current="page">Comment</li>
                                </ol>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
            <!-- ============================================================== -->
            <!-- End Bread crumb and right sidebar toggle -->
            <!-- ============================================================== -->
            <!-- ============================================================== -->
            <!-- Container fluid  -->
            <!-- ============================================================== -->
            <div class="container-fluid">
                <!-- ============================================================== -->
                <!-- Start Page Content -->
                <!-- ============================================================== -->
                <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            @if (count($errors) > 0)
                            <div class="alert alert-danger">
                                <strong>Whoops!</strong> There were some problems with your input.<br><br>
                                <ul>
                                    @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                            @endif
                            <form action="{{route('comment.store')}}" method="post" enctype="multipart/form-data">
                                @csrf
                                <div class="card-body">
                                    <h4 class="card-title">Create Comment</h4>
                                    <input type="hidden" class="form-control" value="{{Auth::user()->id}}" required readonly name="user_id" />


                                    <div class="form-group row">
                                        <label class="col-sm-3 text-right control-label col-form-label">Comment Done
                                            <span class="required text-danger"> * </span></label>
                                        <div class="col-sm-9">
                                             <textarea type="text" name="comment_done"
                                            class="ckeditor form-control @error('comment_done') is-invalid @enderror" placeholder="Comment Done"
                                           >{{old('comment_done','')}}</textarea>
                                           @error('comment_done')
                                           <span class="invalid-feedback" role="alert">
                                               <strong>{{$message}}</strong>
                                           </span>
                                           @enderror
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label class="col-sm-3 text-right control-label col-form-label"> In Response To
                                            <span class="required text-danger"> * </span></label>
                                        <div class="col-sm-9">
                                            <select class="form-control @error('post_id') is-invalid @enderror"
                                            name="post_id">
                                            <option class="bg-info" disabled selected>In response to....</option>
                                            @foreach ($post as $post)
                                            <option value="{{$post->id}}">{{$post->title}}</option>
                                            @endforeach
                                        </select>
                                        @error('post_id')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{$message}}</strong>
                                        </span>
                                        @enderror
                                        </div>
                                    </div>

                                    <div class="form-group row">
                                        <label class="col-sm-3 text-right control-label col-form-label">Submitted On
                                            <span class="required text-danger"> * </span></label>
                                        <div class="col-sm-9">
                                            <input type="date" name="submitted_on"
                                            class="form-control   @error('submitted_on') is-invalid @enderror"
                                            value="{{old('submitted_on','')}}" />
                                        @error('submitted_on')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{$message}}</strong>
                                        </span>
                                        @enderror
                                        </div>
                                    </div>



                                </div>
                                <div class="border-top">
                                    <div class="card-body">
                                        <button type="submit" class="btn btn-primary">Submit</button>
                                    </div>
                                </div>
                            </form>
                        </div>



                    </div>

                </div>
                <!-- editor -->

                <!-- ============================================================== -->
                <!-- End PAge Content -->
                <!-- ============================================================== -->
                <!-- ============================================================== -->
                <!-- Right sidebar -->
                <!-- ============================================================== -->
                <!-- .right-sidebar -->
                <!-- ============================================================== -->
                <!-- End Right sidebar -->
                <!-- ============================================================== -->
            </div>
            <!-- ============================================================== -->
            <!-- End Container fluid  -->

        </div>


        @endsection

resources/views/Backend/Comment/index.blade.php
@extends('Backend.layouts.master')
@section('page_title','Comments')
@section('content')
    <!-- ============================================================== -->
    <div class="page-wrapper">
        <!-- ============================================================== -->
        <!-- Bread crumb and right sidebar toggle -->
        <!-- ============================================================== -->
        <div class="page-breadcrumb">
            <div class="row">
                <div class="col-12 d-flex no-block align-items-center">
                    <h4 class="page-title">Tables</h4>
                    <div class="ml-auto text-right">
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="#">Home</a></li>
                                <li class="breadcrumb-item active" aria-current="page">Comments</li>
                            </ol>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
        <!-- ============================================================== -->
        <!-- End Bread crumb and right sidebar toggle -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Container fluid  -->
        <!-- ============================================================== -->
        <div class="container-fluid">
            <!-- ============================================================== -->
            <!-- Start Page Content -->
            <!-- ============================================================== -->
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            <h3 class="card-title">View Comments</h3>
                            @can('comment-create')
                            <a href="{{ route('comment.create') }}" class="card-title btn btn-success float-right">Add
                                +</a>
                            @endcan
                            <div class="table-responsive">
                                <table id="zero_config" class="table table-striped table-bordered">
                                    <thead>
                                        <tr>
                                            <th>Id</th>
                                            <th>Author</th>
                                            <th>Comment</th>
                                            <th>In Response To</th>
                                            <th>Submitted On</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach ($data as $key => $comment)
                                        <tr>
                                            <td>{{ ++$i }}</td>
                                            <td>{{ $comment->usr['name'] }}</td>
                                            <td>{!!$comment->comment_done!!}</td>
                                            <td>{{$comment->pos['title']}}</td>
                                            <td>{{$comment->submitted_on}}</td>
                                            <td>
                                                <a class="btn btn-info" href="{{ route('comment.show',$comment->id) }}"><i
                                                        class="fa fa-eye"></i></a>
                                                @can('comment-edit')
                                                <a class="btn btn-primary" href="{{ route('comment.edit',$comment->id) }}"><i
                                                        class="fa fa-edit"></i></a>
                                                @endcan
                                                @can('comment-delete')
                                                <button class="btn btn-danger waves-effect waves-light"
                                                    data-target="#deleteComment{{$comment->id}}" data-toggle="modal" type="submit"><i
                                                        class="fa fa-trash-alt"></i></button>
                                                <form action="{{ route('comment.destroy', $comment->id)}}" method="post"
                                                    style="display: inline-block">
                                                    @csrf
                                                    @method('DELETE')
                                                    <div class="row">
                                                        <div class="col-md-4 mt-4">
                                                            <!-- sample modal content -->
                                                            <div id="deleteComment{{$comment->id}}" class="modal fade" tabindex="-1"
                                                                role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                                                                <div class="modal-dialog modal-lg">
                                                                    <div class="modal-content">
                                                                        <div class="modal-header">
                                                                            <div class="row">
                                                                                <div class="col-lg-12 margin-tb">
                                                                                    <div class="pull-left">
                                                                                        <h2>Delete Record ?</h2>
                                                                                    </div>
                                                                                </div>
                                                                            </div>
                                                                            @if (count($errors) > 0)
                                                                            <div class="alert alert-danger">
                                                                                <strong>Whoops!</strong> There were some
                                                                                problems with your
                                                                                input.<br><br>
                                                                                <ul>
                                                                                    @foreach ($errors->all() as $error)
                                                                                    <li>{{ $error }}</li>
                                                                                    @endforeach
                                                                                </ul>
                                                                            </div>
                                                                            @endif
                                                                            <button type="button" class="close" data-dismiss="modal"
                                                                                aria-hidden="true">×</button>
                                                                        </div>
                                                                        <div class="modal-body">
                                                                            <div class="col-xs-12 col-sm-12 col-md-12">
                                                                                <div class="form-group">
                                                                                    <p class="text-danger">Are You Sure ? Once
                                                                                        you delete data, you
                                                                                        cannot get it back.</p>
                                                                                </div>
                                                                            </div>
                                                                        </div>
                                                                        <div class="modal-footer">
                                                                            <button type="button"
                                                                                class="btn btn-secondary waves-effect"
                                                                                data-dismiss="modal">Close</button>
                                                                            <button type="submit"
                                                                                class="btn btn-primary waves-effect waves-light">Delete</button>
                                                                        </div>
                                                                    </div><!-- /.modal-content -->
                                                                </div><!-- /.modal-dialog -->
                                                            </div><!-- /.modal -->
                                                        </div>
                                                    </div>
                                                </form>
                                                @endcan
                                            </td>
                                        </tr>
                                        @endforeach
                                    </tbody>
                                    <tfoot>
                                        <tr>
                                            <th>Id</th>
                                            <th>Author</th>
                                            <th>Comment</th>
                                            <th>In Response To</th>
                                            <th>Submitted On</th>
                                            <th>Action</th>
                                        </tr>
                                    </tfoot>
                                </table>
                            </div>

                        </div>
                    </div>
                </div>
            </div>

    </div>
@endsection

resources/views/Backend/Comment/show.blade.php
@extends('Backend.layouts.master')
@section('page_title',' User')
@section('content')
        <!-- ============================================================== -->
        <div class="page-wrapper">
            <!-- ============================================================== -->
            <!-- Bread crumb and right sidebar toggle -->
            <!-- ============================================================== -->
            <div class="page-breadcrumb">
                <div class="row">
                    <div class="col-12 d-flex no-block align-items-center">
                        <h4 class="page-title">Comment</h4>
                        <div class="ml-auto text-right">
                            <nav aria-label="breadcrumb">
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item"><a href="{{route('dashboard')}}">Home</a></li>
                                    <li class="breadcrumb-item active" aria-current="page">Comment</li>
                                </ol>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
            <!-- ============================================================== -->
            <!-- End Bread crumb and right sidebar toggle -->
            <!-- ============================================================== -->
            <!-- ============================================================== -->
            <!-- Container fluid  -->
            <!-- ============================================================== -->
            <div class="container-fluid">
                <!-- ============================================================== -->
                <!-- Start Page Content -->
                <!-- ============================================================== -->
                <div class="row">
                    <div class="col-md-12">
                        <div class="card">

                                <div class="card-body">
                                    <h4 class="card-title">Comment Details</h4>
                                    <a href="{{ route('comment.index') }}" class="btn btn-success float-right">Back
                                    </a>
                                    <div class="form-group row">
                                        <strong class="col-md-3">Author:</strong>
                                        <div class="col-md-9">
                                           {{$comment->usr['name']}}
                                    </div>
                                    </div>
                                    <div class="form-group row">
                                        <strong class="col-md-3">Comment Done:</strong>
                                        <div class="col-md-9">
                                           {!!$comment->comment_done!!}
                                    </div>
                                    </div>
                                    <div class="form-group row">
                                        <strong class="col-md-3">In Response To:</strong>
                                        <div class="col-md-9">
                                            {{$comment->pos['title']}}
                                    </div>
                                    </div>

                                    <div class="form-group row">
                                        <strong class="col-md-3">Submitted On:</strong>
                                            {{$comment->submitted_on}}
                                        <div class="col-md-9">
                                    </div>
                                    </div>


                                </div>

                        </div>



                    </div>

                </div>
                <!-- editor -->

                <!-- ============================================================== -->
                <!-- End PAge Content -->
                <!-- ============================================================== -->
                <!-- ============================================================== -->
                <!-- Right sidebar -->
                <!-- ============================================================== -->
                <!-- .right-sidebar -->
                <!-- ============================================================== -->
                <!-- End Right sidebar -->
                <!-- ============================================================== -->
            </div>
            <!-- ============================================================== -->
            <!-- End Container fluid  -->

        </div>


        @endsection